language: python

python:
  - "2.7"

jobs:
  include:
  - stage: build and push docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - make build
    - make push

  - stage: deploy production
    script:
      - make deploy server=instance.evarun.ru password=$USER_PASSWORD

addons:
  ssh_known_hosts:
  - instance.evarun.ru
  apt:
    packages:
    - sshpass
    - sox
