apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  SKIP_PREFLIGHT_CHECK: {{ .Values.app.skipPreflightCheck | quote }}
  PGHOST: {{ .Values.app.dbHost | quote }}
  PGPORT: {{ .Values.app.dbPort | quote }}
  PGDATABASE: {{ .Values.app.dbName | quote }}
